services:
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    container_name: connector
    env_file:
      - connector/.env
