"""add received_at to events_raw

Revision ID: 7a905cbd5c44
Revises: a968508ad3f0
Create Date: 2026-08-23 17:05:33.118545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a905cbd5c44'
down_revision: Union[str, Sequence[str], None] = 'a968508ad3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_raw', sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_raw', 'received_at')
    # ### end Alembic commands ###
